### ISSUE TITLE
Linking errors in code_generation.md

### ISSUE THREAD

**Issue by FarzadBT** [myreen/tda283#19]
Seem to have found two issues in code_generation.md:

In the first paragraph there's an incomplete link referring to llvmversion (as well as a missing space) 
`You must use the $llvmversion$\ version in this course; the testsuite has only guaranteed support forthis particular version.`

In the first paragraph under the "An example" title the link "here" redirects back to code_generation.md which does not have a description for the function `fact`
`The following LLVM code demonstrates some of the language features in LLVM. It also serves as an example of what kind of code a Javalette compiler could generate for the fact function described [here](url).`

**Comment by oskarabrahamsson** [comment]
Thanks. 

The project texts were used with some templating system on the old (pre-canvas) course web page, so there's probably more stuff like this lying around. Feel free to post more issues if you run across anything.
